@HostAddress = http://localhost:5255

### get all products
GET http://localhost:5255/products
Content-Type: application/json

### get product by id
GET http://localhost:5255/products/2
Content-Type: application/json

### GET
# GET {{HostAddress}}/user/
# Accept: application/json
# Authorization: Bearer {{AccessToken}}

### get user by id
GET http://localhost:5255/user/9846c653-c02b-4e81-b28c-7564d70dd377

### get users cart
GET http://localhost:5255/user/9846c653-c02b-4e81-b28c-7564d70dd377/cart
Content-Type: application/json

### add item to users cart
POST http://localhost:5255/user/9846c653-c02b-4e81-b28c-7564d70dd377/add-to-cart
Content-Type: application/json

{
  "id": "12831",
  "name": "TEST ETST ETST",
  "description": "High-performance climbing Boots",
  "price": 10,
  "image": "/example-product.webp",
  "size": "XS",
  "quantity": 2
}

### change quantity in users cart
PATCH http://localhost:5255/user/9846c653-c02b-4e81-b28c-7564d70dd377/cart/12831/quantity/6
Content-Type: application/json

### delete an item based on the productId from users cart
DELETE http://localhost:5255/user/9846c653-c02b-4e81-b28c-7564d70dd377/cart/12831
Content-Type: application/json

### delete all items from users cart
DELETE http://localhost:5255/user/9846c653-c02b-4e81-b28c-7564d70dd377/cart

### create a checkout session
curl -X POST http://localhost:5255/create-checkout-session -H "Content-Type: application/json" -d '{}'

### get line items from account page
GET http://localhost:5255/get-line-items?session_id=cs_test_a18NikcS4suKScEY8szTFqY4qc0SRKheRgrIbNcHgdno0fffv82EP2Kjh5

### get metadata from account page
GET http://localhost:5255/get-checkout-session-metadata?session_id=cs_test_a18NikcS4suKScEY8szTFqY4qc0SRKheRgrIbNcHgdno0fffv82EP2Kjh5

### get order items from account page
GET http://localhost:5255/get-shipping-details?session_id=cs_test_a1ZyZFtzL5ZznQap3V8b30S5z0nVGUrwEy4tJcpXQlkeuA3t7vfq1Dwh7t

### add to order
POST http://localhost:5255/user/9846c653-c02b-4e81-b28c-7564d70dd377/add-to-orders
Content-Type: application/json

{
  "id": "hasdfas234",
  "description": "Low-performance climbing Boots",
  "quantity": 2,
  "city": "Denton",
  "country": "USA",
  "line1": "123 Main St",
  "line2": "Apt 1",
  "postal_code": "76201",
  "state": "TX"
}

### get all orders 
GET http://localhost:5255/user/9846c653-c02b-4e81-b28c-7564d70dd377/orders